### ISSUE TITLE
Fastlane Issue

### ISSUE THREAD

**Issue by suho** [anhkul11/Surveys#4]
Hello **Anh**!

Nice to e-meet you 👋  and thanks for your effort on this submission. My name is **Su** - an iOS developer at Nimble and I'd like to conduct the feedbacks via Issues ticket regarding your performance here.

Keep in mind, this is a bidirectional process, so we'd love to hear back from you as well, so please don't hesitate to raise your question or correction in case we missed anything.

If we're aligned on any issue here and you'd like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and we will follow up on those fixes 😇

The first issue I noticed is about **fastlane**, I run your tests with fastlane and got this error message `The scheme 'SurveysTests' is not configured for Running`, please check it.

I hope you find the process enjoyable. Good luck and happy coding 🤘

**Comment by anhkul11** [comment]
Hi @suho!
Thank you for the feedback!
I fixed it in this [PR](https://github.com/anhkul11/Surveys/pull/5) 
Have a nice day!!
