### ISSUE TITLE
Authentication feature issue

### ISSUE THREAD

**Issue by suho** [anhkul11/Surveys#9]
Currently, the app didn't keep the user logged in when they close and open the app again. Could you please tell me the reason why you didn't handle it? And if you handle it, how to implement this feature?

**Comment by anhkul11** [comment]
Actually, I have implemented this feature but decided to comment it out. In `LoginPresenter.swift` line 68~69
```swift
viewDidLoadRelay.subscribe(onNext: { [weak self] in
            self?.view.isShowLoading.accept(true)
            self?.interactor.loginAutomated()
        }).disposed(by: disposeBag)
```
Basically, whenever the app goes to the login screen, it would automatically log in using the email/password that saved from the last successful login.
I commented it out for the users could choose which account they want to log in to. Also, if we somehow notify users that they will be log in automatically by the app, which we don't, so the feature would be appropriate.

**Comment by suho** [comment]
If we use this implementation:
```swift
viewDidLoadRelay.subscribe(onNext: { [weak self] in
            self?.view.isShowLoading.accept(true)
            self?.interactor.loginAutomated()
        }).disposed(by: disposeBag)
```
Then the user still sees the login screen every time they open the app? Can we improve it?

**Comment by anhkul11** [comment]
I think it appropriate to show the user the login screen since it makes better UX, allows the user to aware of what's going on, they can assume that the app is trying to log in.
Although, if we really want to hide the process, we could do the job in the app launched state. Again, it would take some time to make the call and keep the user waiting, wonder "what's taking so long?".
How do you think?

**Comment by suho** [comment]
> I think it appropriate to show the user the login screen since it makes better UX, allows the user to aware of what's going on, they can assume that the app is trying to log in.

I think it will not makes UX better, you can check on some applications on your phone: Facebook, Zalo... Does it show the login screen from the beginning?

> Although, if we really want to hide the process, we could do the job in the app launched state. Again, it would take some time to make the call and keep the user waiting, wonder "what's taking so long?".

In this case, we don't need to make the login request again, just use the access token, and show the home screen directly 😁

**Comment by suho** [comment]
By the way, thank you for all your questions, feedback, and pull requests after my comments. I greatly appreciate it.

**Comment by anhkul11** [comment]
Thank you for all your feedbacks! Love the process
